version: "3.7"

services:
  jenkins:
    image: jenkins/jenkins
    container_name: tender_lamport
    ports:
      - 8080:8080
    volumes:
      - /home/jenkins/jenkins_home:/var/jenkins_home
      - ../../var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  sonar:
    image: sonarqube
    container_name: sonar1
    ports:
      - "9000:9000"
    volumes:
      - /home/sonarqube/data:/opt/sonarqube/data
    restart: on-failure

  nexus:
    image: sonatype/nexus3
    container_name: nexus3
    ports:
      - "8081:8081"
    volumes:
      - /home/nexus/nexus-data:/sonatype-work
      - ../../var/run/docker.sock:/var/run/docker.sock
    restart: on-failure

  prometheus:
    image: prom/prometheus
    restart: unless-stopped
    container_name: prometheus
    ports:
      - "9090:9090"
    volumes:
      - ./prometheus/:/etc/prometheus/
      - prometheus:/prometheus

volumes:
  jenkins:
  sonarqube:
  nexus3:
  prometheus:

  



